title: Aryaman Sinha # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am Aryaman, Electrical Engineering student at IIT Bhubaneswar. My current areas of interest are, Machine Learning, Deep Learning, Computer Vision, Digital Signal Processing.
  <p>
  <a href="https://github.com/as791" class="view" target="_blank">View My GitHub Profile</a>
   <br>
  <a href="https://www.linkedin.com/in/as791/" class="view" target="_blank">View My LinkedIn Profile</a>
  <br>
  <a href="https://drive.google.com/file/d/1FYPK8bDNDb8qEQ9U_1guX7G8EBFhr4gl/view?usp=drivesdk" class="view" target="_blank">View My Resume</a>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
