title: Aryaman Sinha # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am Aryaman, an Electrical Engineering student at IIT Bhubaneswar.
  <br><br>
  <a href="https://www.linkedin.com/in/as791/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
