title: Aryaman Sinha # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am Aryaman, Electrical Engineering student at IIT Bhubaneswar.
  <p>
  <a href="https://www.linkedin.com/in/as791/" class="btn btn-secondary px-4 py-2 btn-sm" target="_blank">LinkedIn</a>
  <a href="https://drive.google.com/file/d/1L4vu8_VWwHFQWodSCV73At8VU2R48Ccz/view?usp=sharing" class="btn btn-secondary px-4 py-2 btn-sm" target="_blank">Résumé</a>
  </p>
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
